const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const labels = {process:'Process',filesystem:'File',network:'Network',dns:'DNS',kubernetes:'Kubernetes',cloudIdentity:'Cloud IAM',api:'API',mcp:'MCP'};
const icons = {process:'⌘',filesystem:'▱',network:'↗',dns:'◉',kubernetes:'◇',cloudIdentity:'♙',api:'⇄',mcp:'✦',principal:'◉',workload:'◇',identity:'♙',resource:'▰',agent:'✦'};
const state = {overview:null,running:false};

async function api(path, options={}) {
  const response = await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
  if(!response.ok){let body={};try{body=await response.json()}catch{};throw new Error(body.error||`Request failed (${response.status})`)}
  return response.json();
}

function fmtDate(value){return new Intl.DateTimeFormat('en',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function scenarioName(value){return ({'identity-gap':'Identity + MCP gap','mcp-gap':'MCP attribution gap','latency-regression':'Telemetry latency','baseline':'Healthy baseline'})[value]||value}
function tone(score){return score>=99.5?'var(--lime)':score>=90?'var(--amber)':'var(--red)'}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}

async function load(){try{state.overview=await api('/api/v1/overview');render(state.overview)}catch(error){toast(error.message);$('#dimension-grid').innerHTML='<p>Could not reach the ContextSLO API.</p>'}}

function render(data){
  const {latest,slo,history}=data;$('#cluster-crumb').textContent=slo.cluster;$('#score-value').textContent=latest.score.toFixed(1);$('#score-target').textContent=`${slo.target.toFixed(1)}%`;$('#score-ring').style.setProperty('--score',latest.score);
  const passing=latest.status==='passing';$('#slo-state').textContent=passing?'WITHIN SLO':'BREACHED';$('#slo-state').className=`metric-chip ${passing?'success':'danger'}`;
  $('#score-delta').textContent=`${latest.regression>0?'+':''}${latest.regression.toFixed(1)} pts`;$('#score-delta').style.color=latest.regression>=0?'var(--lime)':'var(--red)';
  $('#budget-value').textContent=`${latest.errorBudget.consumedRatio.toFixed(0)}%`;$('#budget-bar').style.width=`${Math.min(100,latest.errorBudget.consumedRatio)}%`;$('#budget-allowed').textContent=`${latest.errorBudget.allowed.toFixed(1)}% allowed`;$('#budget-status').textContent=latest.errorBudget.exhausted?'EXHAUSTED':'HEALTHY';$('#budget-status').style.color=latest.errorBudget.exhausted?'var(--red)':'var(--lime)';
  $('#latency-value').textContent=(latest.latencyP95Ms/1000).toFixed(1);$('#latency-target').textContent=`SLO ≤ ${(slo.latencyP95Ms/1000).toFixed(0)}s`;$('#latency-marker').style.left=`${Math.min(98,latest.latencyP95Ms/slo.latencyP95Ms*68)}%`;
  $('#run-count').textContent=data.totalRuns;$('#passing-count').textContent=data.passingRuns;$('#failing-count').textContent=data.totalRuns-data.passingRuns;$('#coverage-average').textContent=`${data.contextCoverage.toFixed(1)}%`;
  $('#marker-value').textContent=latest.marker;$('#graph-subtitle').textContent=`End-to-end attribution for ${slo.service} in ${slo.cluster}.`;
  renderDimensions(latest.dimensions);renderGraph(latest);renderBreaks(latest.breaks);renderChart(history,slo.target);renderFinding(latest.breaks);renderRuns(history);fillSLO(slo);
}

function renderDimensions(dimensions){$('#dimension-grid').innerHTML=dimensions.map(item=>{const t=tone(item.score);return `<article class="dimension-card" style="--coverage:${item.score}%;--tone:${t}"><div class="dimension-icon">${icons[item.dimension]||'•'}</div><strong>${item.score.toFixed(0)}<span>%</span></strong><label>${labels[item.dimension]||item.dimension}</label><small>${item.observed}/${item.expected} observed · ${(item.latencyMs/1000).toFixed(1)}s</small></article>`}).join('')}

function renderGraph(run){const edgeByFrom=Object.fromEntries(run.edges.map(edge=>[edge.from,edge]));let html='';run.nodes.forEach((node,index)=>{html+=`<div class="graph-node"><div class="node-orb">${icons[node.kind]||icons[node.id]||'•'}</div><strong>${node.label}</strong><small>${node.subtitle}</small></div>`;if(index<run.nodes.length-1){const edge=edgeByFrom[node.id]||run.edges[index];html+=`<div class="graph-edge ${edge&&!edge.preserved?'broken':''}"><span>${edge?.label||'context'}</span></div>`}});$('#evidence-graph').innerHTML=html}

function renderBreaks(breaks){$('#break-list').innerHTML=breaks.length?breaks.map(item=>`<article class="context-break"><div class="break-icon">!</div><div><h3>${item.from} → ${item.to}<span>${item.dimension}</span></h3><p>${item.explanation}</p></div><small><b>Suggested:</b> ${item.remediation}</small></article>`).join(''):'<div class="no-break"><i>✓</i> Context is preserved across every required hop.</div>'}

function renderFinding(breaks){const el=$('#finding-body');const severity=$('.finding-severity');if(!breaks.length){severity.textContent='CLEAR';severity.style.color='var(--lime)';el.innerHTML='<div class="finding-path">No context breaks</div><p>The latest synthetic journey retained complete workload, process, identity, API, and cloud attribution.</p>';return}severity.textContent='HIGH';severity.style.color='var(--red)';const item=breaks[0];el.innerHTML=`<div class="finding-path"><span>${item.from}</span><i>— — ✕ — —</i><span>${item.to}</span></div><p>${item.explanation}</p><div class="remediation"><span>RECOMMENDED NEXT STEP</span><p>${item.remediation}</p></div>`}

function renderRuns(runs){$('#runs-table').innerHTML=runs.slice(0,8).map(run=>`<tr><td><strong>${fmtDate(run.completedAt)}</strong><small><code>${run.marker}</code> · ${run.id}</small></td><td>${scenarioName(run.scenario)}</td><td><span class="table-score">${run.score.toFixed(1)}%</span></td><td>${(run.latencyP95Ms/1000).toFixed(2)}s</td><td>${run.breaks.length}</td><td><span class="status-badge ${run.status}">${run.status}</span></td></tr>`).join('')}

function renderChart(runs,target){const svg=$('#history-chart');const values=[...runs].slice(0,12).reverse();if(!values.length){svg.innerHTML='';return}const W=720,H=210,pad={l:34,r:14,t:18,b:26},min=65,max=101,x=i=>pad.l+(W-pad.l-pad.r)*(values.length===1?.5:i/(values.length-1)),y=v=>pad.t+(H-pad.t-pad.b)*(max-v)/(max-min);const pts=values.map((r,i)=>[x(i),y(r.score)]);const line=pts.map((p,i)=>`${i?'L':'M'}${p[0]},${p[1]}`).join(' ');const area=`${line} L${pts.at(-1)[0]},${H-pad.b} L${pts[0][0]},${H-pad.b} Z`;let grid='';[70,80,90,100].forEach(v=>{grid+=`<line class="chart-grid" x1="${pad.l}" y1="${y(v)}" x2="${W-pad.r}" y2="${y(v)}"/><text class="chart-label" x="0" y="${y(v)+3}">${v}%</text>`});svg.innerHTML=`<defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="var(--lime)" stop-opacity=".18"/><stop offset="1" stop-color="var(--lime)" stop-opacity="0"/></linearGradient></defs>${grid}<line class="chart-target" x1="${pad.l}" y1="${y(target)}" x2="${W-pad.r}" y2="${y(target)}"/><text class="chart-label" x="${W-70}" y="${y(target)-5}">SLO ${target}%</text><path class="chart-area" d="${area}"/><path class="chart-line" d="${line}"/>${pts.map((p,i)=>`<circle class="chart-point" cx="${p[0]}" cy="${p[1]}" r="3"><title>${values[i].score}% · ${scenarioName(values[i].scenario)}</title></circle>`).join('')}`}

async function runValidation(){if(state.running)return;state.running=true;const button=$('#run-validation');button.disabled=true;const dialog=$('#run-dialog');const scenario=$('#scenario').value;const phases=[['⌘','Process'],['▱','File'],['◉','DNS'],['↗','Network'],['◇','Kubernetes'],['⇄','API'],['♙','Cloud IAM'],['✦','MCP']];$('#run-steps').innerHTML=phases.map(([icon,label])=>`<div class="run-step"><i>${icon}</i>${label}</div>`).join('');$('#run-marker').textContent='Allocating signed marker…';$('#dialog-progress-bar').style.width='0';dialog.showModal();const steps=$$('.run-step');for(let i=0;i<steps.length;i++){if(i)steps[i-1].classList.replace('active','done');steps[i].classList.add('active');$('#dialog-progress-bar').style.width=`${(i+1)/steps.length*82}%`;$('#run-marker').textContent=`Ground truth captured · step ${i+1}/${steps.length}`;await new Promise(r=>setTimeout(r,150))}
  try{const run=await api('/api/v1/runs',{method:'POST',body:JSON.stringify({scenario})});steps.at(-1).classList.replace('active','done');$('#dialog-progress-bar').style.width='100%';$('#run-marker').textContent=`${run.marker} · ${run.score.toFixed(1)}% context integrity`;await new Promise(r=>setTimeout(r,650));dialog.close();await load();toast(run.status==='passing'?'Validation passed — full context preserved':`${run.breaks.length} context break${run.breaks.length===1?'':'s'} detected`)}catch(error){dialog.close();toast(error.message)}finally{state.running=false;button.disabled=false}}

function fillSLO(slo){$('#slo-name').value=slo.name;$('#slo-service').value=slo.service;$('#slo-target').value=slo.target;$('#slo-latency').value=slo.latencyP95Ms;$('#required-context').innerHTML=slo.requiredContext.map(item=>`<span class="context-tag">✓ ${labels[item]||item}</span>`).join('')}
async function saveSLO(event){event.preventDefault();const current=state.overview.slo;const next={...current,name:$('#slo-name').value.trim(),service:$('#slo-service').value.trim(),target:Number($('#slo-target').value),latencyP95Ms:Number($('#slo-latency').value)};try{await api('/api/v1/slo',{method:'PUT',body:JSON.stringify(next)});$('#slo-dialog').close();await load();toast('Security Context SLO updated')}catch(error){toast(error.message)}}

$('#run-validation').addEventListener('click',runValidation);$('#edit-slo').addEventListener('click',()=>$('#slo-dialog').showModal());$('#slo-form').addEventListener('submit',saveSLO);$('#copy-marker').addEventListener('click',async()=>{await navigator.clipboard.writeText($('#marker-value').textContent);toast('Marker copied')});
$('#export-json').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state.overview,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`contextslo-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Validation report exported')});
$('#theme-toggle').addEventListener('click',()=>{const root=document.documentElement,next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;localStorage.setItem('contextslo-theme',next)});document.documentElement.dataset.theme=localStorage.getItem('contextslo-theme')||'dark';
$$('.nav-item[data-section]').forEach(item=>item.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));item.classList.add('active')}));load();
