apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crd.yaml
  - rbac.yaml
  - pvc.yaml
  - deployment.yaml
  - operator.yaml
  - service.yaml
  - network-policy.yaml
  - sample-slo.yaml
